export const daySeeds = [
  { dayNumber: 1, date: '2026-09-27', title: 'Vuelo a Fukuoka', summary: 'Salida hacia Fukuoka con escala en Hong Kong.' },
  { dayNumber: 2, date: '2026-09-28', title: 'Fukuoka: llegada y Hakata', summary: 'Llegada a Fukuoka, check-in en Hakata y primera noche tranquila entre Kushida Shrine, Canal City y los yatai de Nakasu.' },
  { dayNumber: 3, date: '2026-09-29', title: 'Fukuoka: día completo', summary: 'Día completo en Fukuoka: Ohori Park, ruinas del castillo, Tenjin, Momochi Seaside Park y Fukuoka Tower al atardecer.' },
  { dayNumber: 4, date: '2026-09-30', title: 'Hakata → Yufuin', summary: 'Mañana suave por Hakata antes de tomar el Yufuin no Mori hacia Yufuin, con margen para llegar antes del check-in.' },
  { dayNumber: 5, date: '2026-10-01', title: 'Yufuin → Beppu', summary: 'Yufuin a Beppu sin traslado largo: paseo final, Hells of Beppu, comida jigoku mushi, Kannawa y onsen.' },
  { dayNumber: 6, date: '2026-10-02', title: 'Beppu → Matsuyama (Shikoku)', summary: 'Cruce hacia Shikoku: ferry Beppu a Yawatahama, llegada a Matsuyama, Matsuyama Castle, Dogo Onsen y cena de tai-meshi.' },
  { dayNumber: 7, date: '2026-10-03', title: 'Matsuyama → Takamatsu', summary: 'Matsuyama a Takamatsu, Sanuki udon, Ritsurin Garden y paseo por Tamamo Park, puerto y zona comercial.' },
  { dayNumber: 8, date: '2026-10-04', title: 'Naoshima → Kurashiki', summary: 'Naoshima como gran día Setouchi: Chichu Art Museum, Benesse House, pumpkins, Art House Project, salida por Uno y noche en Kurashiki.' },
  { dayNumber: 9, date: '2026-10-05', title: 'Kurashiki → Osaka', summary: 'Mañana en Kurashiki Bikan, traslado vía Okayama y llegada a Osaka para seguir con Osaka Castle, Namba y Dotonbori.' },
  { dayNumber: 10, date: '2026-10-06', title: 'Universal Studios Japan', summary: 'Día completo en Universal Studios Japan. Llegar 60-90 minutos antes de la apertura oficial y priorizar Super Nintendo World, Harry Potter y atracciones principales.' },
  { dayNumber: 11, date: '2026-10-07', title: 'Osaka: gastronomía y barrios', summary: 'Día gastronómico y urbano por Osaka: Kuromon, Den Den Town, Shinsekai, Shinsaibashi, Amerikamura y cierre recomendado en Umeda Sky Building.' },
  { dayNumber: 12, date: '2026-10-08', title: 'Nagoya', summary: 'Día completo en Nagoya: castillo, Osu, Atsuta Jingu, Sakae y cena de hitsumabushi.' },
  { dayNumber: 13, date: '2026-10-09', title: 'Nakasendō: Magome–Tsumago', summary: 'Excursión por la Nakasendō: Nagoya, Nakatsugawa, Magome, caminata hasta Tsumago, Nagiso y regreso a Nagoya.' },
  { dayNumber: 14, date: '2026-10-10', title: 'Hakone', summary: 'Ruta circular clásica de Hakone en sábado: Owakudani, vistas del Fuji, Lago Ashi, Hakone Shrine, paseo por la antigua Tokaido y onsen.' },
  { dayNumber: 15, date: '2026-10-11', title: 'Hakone → Tokio + Akihabara', summary: 'Llegada tranquila a Tokio desde Hakone: dejar equipaje, Asakusa, Sumida River y tarde-noche de electrónica, retro gaming y arcades en Akihabara.' },
  { dayNumber: 16, date: '2026-10-12', title: 'Tokio: Harajuku–Shibuya', summary: 'Tokio moderno en Sports Day: Meiji Jingu, Harajuku, Omotesando, Shibuya, Shibuya Sky y noche en Shinjuku.' },
  { dayNumber: 17, date: '2026-10-13', title: 'Kamakura y Enoshima', summary: 'Excursión a Kamakura y Enoshima: santuarios, Komachi-dori, Enoden, Gran Buda, Hasedera, costa y puesta de sol.' },
  { dayNumber: 18, date: '2026-10-14', title: 'Tokyo DisneySea', summary: 'Día completo en Tokyo DisneySea, llegando sobre las 08:00 para hacer cola antes de la apertura oficial.' },
  { dayNumber: 19, date: '2026-10-15', title: 'Tokio: último día completo', summary: 'Último día completo en Tokio: Tsukiji, Ginza, Tokyo Station, teamLab Borderless, Azabudai Hills, Tokyo Tower y Roppongi.' },
  { dayNumber: 20, date: '2026-10-16', title: 'Regreso a Barcelona', summary: 'Últimas compras por la mañana, recogida de maletas y llegada a Narita sobre las 13:00 para el vuelo de regreso.' },
] as const;

export type ActivitySeed = {
  dayNumber: number;
  time: string | null;
  type: 'transport' | 'place' | 'event' | 'comida' | 'nota' | 'aviso' | 'hotel';
  title: string;
  description: string | null;
  status: 'programado' | 'confirmado' | 'pendiente' | null;
  cost: number | null;
  currency: 'EUR' | 'JPY' | null;
  durationMin: number | null;
  origin: string | null;
  destination: string | null;
  originLat: number | null;
  originLng: number | null;
  destLat: number | null;
  destLng: number | null;
  viaLabel?: string | null;
  viaLat?: number | null;
  viaLng?: number | null;
};

const BLANK: Pick<
  ActivitySeed,
  'status' | 'cost' | 'currency' | 'durationMin' | 'origin' | 'destination' | 'originLat' | 'originLng' | 'destLat' | 'destLng'
> = {
  status: null,
  cost: null,
  currency: null,
  durationMin: null,
  origin: null,
  destination: null,
  originLat: null,
  originLng: null,
  destLat: null,
  destLng: null,
};

export const activitySeeds: ActivitySeed[] = [
  // Día 1
  {
    dayNumber: 1,
    time: '13:00',
    type: 'transport',
    title: 'Barcelona - Fukuoka',
    description:
      'Vuelo internacional con escala en Hong Kong (Cathay Pacific CX318 / CX588). No necesitas recoger equipaje y volver a facturarlo.',
    status: 'programado',
    cost: 2479.75,
    currency: 'EUR',
    durationMin: 1170,
    origin: 'BCN Aeropuerto Josep Tarradellas Barcelona-El Prat T2',
    destination: 'Fukuoka Airport',
    originLat: 41.2971,
    originLng: 2.0785,
    destLat: 33.5859,
    destLng: 130.4506,
    viaLabel: 'Escala en Hong Kong',
    viaLat: 22.308,
    viaLng: 113.9185,
  },

  // Día 2
  {
    dayNumber: 2,
    time: '16:30',
    type: 'transport',
    title: 'Aeropuerto de Fukuoka - Hakata',
    description: 'Llegada, inmigración, recogida de equipaje y traslado hacia Hakata para hacer check-in y dejar maletas.',
    ...BLANK,
    durationMin: 90,
    origin: 'Aeropuerto de Fukuoka',
    destination: 'Hakata',
    originLat: 33.5859,
    originLng: 130.4506,
    destLat: 33.5902,
    destLng: 130.4207,
  },
  {
    dayNumber: 2,
    time: '18:00',
    type: 'place',
    title: 'Kushida Shrine + paseo por Hakata',
    description: 'Primer contacto tranquilo con la ciudad. Kushida Shrine está muy cerca de Canal City.',
    ...BLANK,
    destLat: 33.5926,
    destLng: 130.4108,
  },
  {
    dayNumber: 2,
    time: '19:00',
    type: 'event',
    title: 'Canal City Hakata',
    description: 'Paseo por el complejo, arquitectura, tiendas y zona del canal. Suele operar hasta aproximadamente las 21:00.',
    ...BLANK,
    destLat: 33.5898,
    destLng: 130.4105,
  },
  {
    dayNumber: 2,
    time: '20:00',
    type: 'comida',
    title: 'Yatai de Nakasu',
    description: 'Cena en puestos callejeros junto al río. Probar Hakata tonkotsu ramen, yakitori, mentaiko, gyoza y cerveza japonesa.',
    ...BLANK,
    destLat: 33.5936,
    destLng: 130.4069,
  },
  {
    dayNumber: 2,
    time: '22:00',
    type: 'nota',
    title: 'Nakasu nocturno',
    description: 'Paseo junto al río y regreso tranquilo al hotel.',
    ...BLANK,
  },
  {
    dayNumber: 2,
    time: null,
    type: 'hotel',
    title: 'Hotel Torifito Hakata Gion',
    description:
      'Reserva de 2 noches en Fukuoka. Entrada lunes 28 desde las 15:00, salida miércoles 30 hasta las 11:00. Coste: 163,00 € (registrado en la ficha de alojamiento).',
    ...BLANK,
    status: 'programado',
    destLat: 33.5926,
    destLng: 130.4159,
  },

  // Día 3
  {
    dayNumber: 3,
    time: '08:00',
    type: 'comida',
    title: 'Desayuno japonés en Hakata',
    description: 'Buscar desayuno por Hakata: pescado, arroz, sopa miso o tamagoyaki.',
    ...BLANK,
    destLat: 33.5902,
    destLng: 130.4207,
  },
  {
    dayNumber: 3,
    time: '09:00',
    type: 'place',
    title: 'Ohori Park',
    description: 'Metro desde Hakata hasta Ohorikoen. Parque con gran lago e islas conectadas por pequeños puentes.',
    ...BLANK,
    destLat: 33.5847,
    destLng: 130.3813,
  },
  {
    dayNumber: 3,
    time: '10:30',
    type: 'place',
    title: 'Ruinas del Castillo de Fukuoka + Maizuru Park',
    description: 'Visita junto a Ohori Park para no perder tiempo en transporte.',
    ...BLANK,
    destLat: 33.5857,
    destLng: 130.3789,
  },
  {
    dayNumber: 3,
    time: '11:30',
    type: 'nota',
    title: 'Akasaka / Tenjin',
    description: 'Zona urbana agradable para ir entrando en la parte comercial de Fukuoka.',
    ...BLANK,
    destLat: 33.5902,
    destLng: 130.3987,
  },
  {
    dayNumber: 3,
    time: '12:30',
    type: 'comida',
    title: 'Motsunabe o Hakata ramen',
    description: 'Prioridad: motsunabe, hot pot de vísceras característico de Fukuoka. Alternativa: Hakata ramen.',
    ...BLANK,
    destLat: 33.5902,
    destLng: 130.3987,
  },
  {
    dayNumber: 3,
    time: '14:00',
    type: 'place',
    title: 'Tenjin + Daimyo',
    description: 'Zona comercial y juvenil: tiendas japonesas, cafés, ropa, electrónica y hobbies.',
    ...BLANK,
    destLat: 33.5902,
    destLng: 130.3987,
  },
  {
    dayNumber: 3,
    time: '16:00',
    type: 'transport',
    title: 'Traslado hacia Momochi',
    description: 'Metro o bus desde Tenjin hacia la costa.',
    ...BLANK,
    durationMin: 60,
    origin: 'Tenjin',
    destination: 'Momochi',
    originLat: 33.5902,
    originLng: 130.3987,
    destLat: 33.5934,
    destLng: 130.3489,
  },
  {
    dayNumber: 3,
    time: '17:00',
    type: 'place',
    title: 'Momochi Seaside Park',
    description: 'Paseo por la playa y la zona marítima.',
    ...BLANK,
    destLat: 33.5934,
    destLng: 130.3489,
  },
  {
    dayNumber: 3,
    time: '18:30',
    type: 'event',
    title: 'Fukuoka Tower',
    description: 'Subida al atardecer para ver Fukuoka pasar de día a noche. Observatorio a unos 123 m; opera aproximadamente de 09:30 a 22:00.',
    ...BLANK,
    destLat: 33.5933,
    destLng: 130.3489,
  },
  {
    dayNumber: 3,
    time: '20:00',
    type: 'transport',
    title: 'Regreso a Hakata',
    description: 'Vuelta desde Momochi/Fukuoka Tower hacia Hakata.',
    ...BLANK,
    durationMin: 60,
    origin: 'Momochi',
    destination: 'Hakata',
    originLat: 33.5933,
    originLng: 130.3489,
    destLat: 33.5902,
    destLng: 130.4207,
  },
  {
    dayNumber: 3,
    time: '21:00',
    type: 'comida',
    title: 'Cena: motsunabe o Hakata ramen',
    description: 'Si el día anterior fue ramen, cenar motsunabe. Si ya hubo motsunabe, buscar Hakata ramen.',
    ...BLANK,
    destLat: 33.5902,
    destLng: 130.4207,
  },

  // Día 4
  {
    dayNumber: 4,
    time: '07:30',
    type: 'comida',
    title: 'Desayuno en Hakata',
    description: 'Desayuno temprano antes de cerrar maletas y moverse hacia la estación.',
    ...BLANK,
    destLat: 33.5902,
    destLng: 130.4207,
  },
  {
    dayNumber: 4,
    time: '08:30',
    type: 'place',
    title: 'Paseo corto por Hakata y Sumiyoshi Shrine',
    description: 'Ruta suave por Hakata Station, Sumiyoshi Shrine y alrededores del hotel.',
    ...BLANK,
    destLat: 33.5902,
    destLng: 130.4207,
  },
  {
    dayNumber: 4,
    time: '09:15',
    type: 'nota',
    title: 'Volver al hotel y recoger equipaje',
    description: 'Volver al hotel, recoger maletas y salir hacia Hakata Station con margen.',
    ...BLANK,
  },
  {
    dayNumber: 4,
    time: '09:40',
    type: 'aviso',
    title: 'Estar en el andén con margen',
    description: 'Llegar a Hakata Station entre 09:40 y 10:00 para tomar el Yufuin no Mori con calma.',
    ...BLANK,
  },
  {
    dayNumber: 4,
    time: '10:11',
    type: 'transport',
    title: 'Yufuin no Mori 3',
    description:
      'Tren turístico de JR Kyushu (servicio "Yufuin no Mori 3"). Hakata 10:11 - Yufuin 12:32; deja más de 1 hora de margen antes de las 14:00.',
    ...BLANK,
    durationMin: 141,
    origin: 'Hakata Station',
    destination: 'Yufuin Station',
    originLat: 33.5902,
    originLng: 130.4207,
    destLat: 33.2645,
    destLng: 131.3626,
  },
  {
    dayNumber: 4,
    time: '12:32',
    type: 'place',
    title: 'Llegada a Yufuin y paseo antes del check-in',
    description: 'Tiempo para caminar o comer algo antes de estar en Yufuin a las 14:00.',
    ...BLANK,
    destLat: 33.2645,
    destLng: 131.3626,
  },
  {
    dayNumber: 4,
    time: null,
    type: 'hotel',
    title: 'Yufuin Onsen Toshoan',
    description:
      'Ryokan onsen reservado en Yufu. Entrada miércoles 30 de septiembre de 15:00 a 17:00. Salida jueves 1 de octubre de 08:00 a 11:00. Coste: 303,00 € (registrado en la ficha de alojamiento).',
    ...BLANK,
    status: 'programado',
    destLat: 33.2645,
    destLng: 131.3626,
  },

  // Día 5
  {
    dayNumber: 5,
    time: '08:00',
    type: 'place',
    title: 'Yufuin: desayuno y último paseo',
    description: 'Desayuno tranquilo y último paseo por Yufuin antes de moverse hacia Beppu.',
    ...BLANK,
    destLat: 33.2645,
    destLng: 131.3626,
  },
  {
    dayNumber: 5,
    time: '10:00',
    type: 'transport',
    title: 'Yufuin - Beppu',
    description: 'Bus o tren según combinación. Evitar un traslado largo porque venís de dormir en Yufuin.',
    ...BLANK,
    durationMin: 90,
    origin: 'Yufuin Station',
    destination: 'Beppu',
    originLat: 33.2645,
    originLng: 131.3626,
    destLat: 33.2846,
    destLng: 131.4914,
  },
  {
    dayNumber: 5,
    time: '12:00',
    type: 'event',
    title: 'Beppu Jigoku',
    description:
      'Visitar varios Hells of Beppu sin intentar verlos todos. Prioridad: Umi Jigoku; Chinoike Jigoku; Tatsumaki Jigoku.',
    ...BLANK,
    destLat: 33.2965,
    destLng: 131.4989,
  },
  {
    dayNumber: 5,
    time: '14:00',
    type: 'comida',
    title: 'Jigoku mushi',
    description: 'Probar comida cocinada utilizando vapor geotérmico.',
    ...BLANK,
    destLat: 33.2965,
    destLng: 131.4989,
  },
  {
    dayNumber: 5,
    time: '15:00',
    type: 'place',
    title: 'Kannawa',
    description: 'Pasear por calles llenas de vapor. Beppu tiene un ambiente termal distinto a Yufuin.',
    ...BLANK,
    destLat: 33.2965,
    destLng: 131.4989,
  },
  {
    dayNumber: 5,
    time: '17:00',
    type: 'event',
    title: 'Onsen en Beppu',
    description: 'Cerrar el día con onsen y dormir en Beppu.',
    ...BLANK,
    destLat: 33.2846,
    destLng: 131.4914,
  },
  {
    dayNumber: 5,
    time: null,
    type: 'hotel',
    title: 'Hotel Arthur KITAHAMA BASE',
    description:
      'Estancia de 1 noche, habitación cama grande, 2 adultos. Check-in 1 oct desde 17:00, check-out 2 oct hasta 12:00. Dirección: Kitahama 1-2-5, Beppu, Oita, Japón.',
    ...BLANK,
    status: 'confirmado',
    destLat: 33.2846,
    destLng: 131.4914,
  },

  // Día 6
  {
    dayNumber: 6,
    time: '07:00',
    type: 'nota',
    title: 'Desayuno y check-out en Beppu',
    description: 'Desayuno temprano y check-out antes de cruzar hacia Shikoku.',
    ...BLANK,
    destLat: 33.2846,
    destLng: 131.4914,
  },
  {
    dayNumber: 6,
    time: '09:45',
    type: 'transport',
    title: 'Ferry Beppu - Yawatahama',
    description: 'Uwajima Unyu opera el servicio Beppu 09:45 - Yawatahama 12:30. El transporte forma parte del viaje.',
    ...BLANK,
    durationMin: 165,
    origin: 'Beppu Port',
    destination: 'Yawatahama',
    originLat: 33.2801,
    originLng: 131.4975,
    destLat: 33.4614,
    destLng: 132.4136,
  },
  {
    dayNumber: 6,
    time: '12:30',
    type: 'transport',
    title: 'Yawatahama - Matsuyama',
    description: 'Continuar desde Yawatahama hacia Matsuyama.',
    ...BLANK,
    durationMin: 120,
    origin: 'Yawatahama',
    destination: 'Matsuyama',
    originLat: 33.4614,
    originLng: 132.4136,
    destLat: 33.8392,
    destLng: 132.7657,
  },
  {
    dayNumber: 6,
    time: '15:00',
    type: 'place',
    title: 'Matsuyama Castle',
    description: 'Castillo original sobre la montaña. Mejor priorizar Matsuyama Castle antes que meter otra gran ciudad.',
    ...BLANK,
    destLat: 33.8433,
    destLng: 132.7658,
  },
  {
    dayNumber: 6,
    time: '17:30',
    type: 'event',
    title: 'Dogo Onsen',
    description:
      'Paseo por Dogo Onsen Honkan, calles tradicionales, Botchan Karakuri Clock y comercios. Uno de los grandes barrios termales históricos de Japón.',
    ...BLANK,
    destLat: 33.8515,
    destLng: 132.7867,
  },
  {
    dayNumber: 6,
    time: '19:00',
    type: 'comida',
    title: 'Tai-meshi',
    description: 'Buscar tai-meshi, arroz con dorada y especialidad de Ehime.',
    ...BLANK,
    destLat: 33.8392,
    destLng: 132.7657,
  },
  {
    dayNumber: 6,
    time: null,
    type: 'hotel',
    title: 'Dormir en Matsuyama',
    description: 'Alojamiento pendiente por definir en Matsuyama.',
    ...BLANK,
    status: 'pendiente',
    destLat: 33.8392,
    destLng: 132.7657,
  },

  // Día 7
  {
    dayNumber: 7,
    time: '08:00',
    type: 'place',
    title: 'Matsuyama: desayuno y paseo',
    description: 'Mañana tranquila antes de cruzar Shikoku hacia el este.',
    ...BLANK,
    destLat: 33.8392,
    destLng: 132.7657,
  },
  {
    dayNumber: 7,
    time: '10:00',
    type: 'transport',
    title: 'Matsuyama - Takamatsu',
    description: 'Atravesar Shikoku hacia el este (operador JR Shikoku).',
    ...BLANK,
    durationMin: 150,
    origin: 'Matsuyama Station',
    destination: 'Takamatsu',
    originLat: 33.8392,
    originLng: 132.7657,
    destLat: 34.3401,
    destLng: 134.0466,
  },
  {
    dayNumber: 7,
    time: '13:00',
    type: 'comida',
    title: 'Sanuki udon',
    description: 'Takamatsu está en Kagawa, prácticamente la patria del Sanuki udon. Buscar un restaurante local sencillo.',
    ...BLANK,
    destLat: 34.3401,
    destLng: 134.0466,
  },
  {
    dayNumber: 7,
    time: '15:00',
    type: 'place',
    title: 'Ritsurin Garden',
    description:
      'Jardín tradicional enorme con estanques, puentes, pinos, pequeñas colinas y vistas del monte Shiun. Aporta equilibrio antes de Osaka y Tokio.',
    ...BLANK,
    destLat: 34.3306,
    destLng: 134.0311,
  },
  {
    dayNumber: 7,
    time: '17:30',
    type: 'place',
    title: 'Takamatsu: Tamamo Park, puerto y zona comercial',
    description: 'Paseo por Tamamo Park, puerto, Takamatsu Castle y zona comercial.',
    ...BLANK,
    destLat: 34.3486,
    destLng: 134.0505,
  },
  {
    dayNumber: 7,
    time: '19:00',
    type: 'comida',
    title: 'Cena en Takamatsu',
    description: 'Más udon si apetece o pescado de Setouchi.',
    ...BLANK,
    destLat: 34.3401,
    destLng: 134.0466,
  },
  {
    dayNumber: 7,
    time: null,
    type: 'hotel',
    title: 'Dormir en Takamatsu',
    description: 'Alojamiento pendiente por definir en Takamatsu.',
    ...BLANK,
    status: 'pendiente',
    destLat: 34.3401,
    destLng: 134.0466,
  },

  // Día 8
  {
    dayNumber: 8,
    time: '07:30',
    type: 'transport',
    title: 'Ferry Takamatsu - Naoshima',
    description: 'Salida temprana desde Takamatsu Port hacia Naoshima.',
    ...BLANK,
    durationMin: 90,
    origin: 'Takamatsu Port',
    destination: 'Naoshima',
    originLat: 34.3553,
    originLng: 134.0508,
    destLat: 34.4606,
    destLng: 133.9975,
  },
  {
    dayNumber: 8,
    time: '09:00',
    type: 'event',
    title: 'Naoshima',
    description:
      'Isla, naturaleza, arquitectura, mar y arte. Prioridades: Chichu Art Museum; Benesse House Museum; Yellow Pumpkin; Red Pumpkin; Art House Project; Honmura. Nota: reservar Chichu con antelación.',
    ...BLANK,
    status: 'pendiente',
    destLat: 34.4606,
    destLng: 133.9975,
  },
  {
    dayNumber: 8,
    time: '10:00',
    type: 'place',
    title: 'Chichu Art Museum',
    description: 'Museo construido prácticamente bajo tierra, diseñado por Tadao Ando.',
    ...BLANK,
    destLat: 34.4553,
    destLng: 134.0022,
  },
  {
    dayNumber: 8,
    time: '15:30',
    type: 'transport',
    title: 'Naoshima - Uno',
    description: 'No volver a Takamatsu. Salir por Uno, ya en Honshu, para seguir avanzando hacia Osaka.',
    ...BLANK,
    durationMin: 90,
    origin: 'Naoshima',
    destination: 'Uno',
    originLat: 34.4606,
    originLng: 133.9975,
    destLat: 34.4903,
    destLng: 133.9494,
  },
  {
    dayNumber: 8,
    time: '17:00',
    type: 'transport',
    title: 'Uno - Kurashiki',
    description: 'Llegada a Kurashiki para dormir allí y avanzar hacia Osaka al día siguiente.',
    ...BLANK,
    durationMin: 90,
    origin: 'Uno Station',
    destination: 'Kurashiki',
    originLat: 34.4903,
    originLng: 133.9494,
    destLat: 34.5847,
    destLng: 133.772,
  },
  {
    dayNumber: 8,
    time: '18:30',
    type: 'place',
    title: 'Kurashiki Bikan nocturno',
    description: 'Aunque las tiendas cierren, el distrito Bikan queda precioso: canal, casas tradicionales e iluminación.',
    ...BLANK,
    destLat: 34.5936,
    destLng: 133.7724,
  },
  {
    dayNumber: 8,
    time: null,
    type: 'hotel',
    title: 'Dormir en Kurashiki',
    description: 'Alojamiento pendiente por definir en Kurashiki.',
    ...BLANK,
    status: 'pendiente',
    destLat: 34.5847,
    destLng: 133.772,
  },

  // Día 9
  {
    dayNumber: 9,
    time: '08:00',
    type: 'place',
    title: 'Kurashiki Bikan',
    description:
      'Recorrer el distrito histórico: canal, casas blancas, sauces, cafés, tiendas tradicionales, Ivy Square y tiendas de índigo/denim japonés.',
    ...BLANK,
    destLat: 34.5936,
    destLng: 133.7724,
  },
  {
    dayNumber: 9,
    time: '11:00',
    type: 'transport',
    title: 'Kurashiki - Okayama',
    description: 'Traslado hacia Okayama. Si apetece, comer algo rápido allí.',
    ...BLANK,
    durationMin: 60,
    origin: 'Kurashiki Station',
    destination: 'Okayama',
    originLat: 34.5972,
    originLng: 133.7688,
    destLat: 34.6551,
    destLng: 133.9195,
  },
  {
    dayNumber: 9,
    time: '12:00',
    type: 'transport',
    title: 'Okayama - Shin-Osaka',
    description: 'Shinkansen (operador JR) hacia Osaka para enlazar con el plan de la tarde.',
    ...BLANK,
    durationMin: 60,
    origin: 'Okayama Station',
    destination: 'Shin-Osaka',
    originLat: 34.6551,
    originLng: 133.9195,
    destLat: 34.7338,
    destLng: 135.5002,
  },
  {
    dayNumber: 9,
    time: '13:00',
    type: 'nota',
    title: 'Llegada a Osaka + hotel',
    description: 'Llegada a Osaka, dejar maletas y preparar una tarde centrada en Osaka Castle, Namba y Dotonbori.',
    ...BLANK,
    destLat: 34.6937,
    destLng: 135.5023,
  },
  {
    dayNumber: 9,
    time: '13:30',
    type: 'place',
    title: 'Osaka Castle + parque',
    description:
      'Dedicar unas 3 horas incluyendo jardines y exteriores. Ruta: Osakajokoen, Osaka Castle Park, castillo y jardines. El museo abre de 09:00 a 18:00 con última entrada 30 minutos antes.',
    ...BLANK,
    destLat: 34.6873,
    destLng: 135.5262,
  },
  {
    dayNumber: 9,
    time: '17:00',
    type: 'place',
    title: 'Namba Yasaka Shrine',
    description: 'Santuario famoso por la enorme cabeza de león. Visita corta antes de entrar en la zona de Dotonbori.',
    ...BLANK,
    destLat: 34.658,
    destLng: 135.5023,
  },
  {
    dayNumber: 9,
    time: '18:00',
    type: 'place',
    title: 'Hozenji Yokocho',
    description: 'Callejones estrechos, faroles, restaurantes pequeños y templo Hozenji. Perfecto para cambiar de ambiente antes de Dotonbori.',
    ...BLANK,
    destLat: 34.6685,
    destLng: 135.5013,
  },
  {
    dayNumber: 9,
    time: '19:00',
    type: 'comida',
    title: 'Dotonbori + cena por puestos',
    description:
      'Recorrido por Glico Man, Ebisu Bridge, canal, Don Quijote y callejones de Namba. Cena en ruta: takoyaki, okonomiyaki, kushikatsu, gyoza y cheesecake japonés si queda sitio.',
    ...BLANK,
    destLat: 34.6687,
    destLng: 135.5013,
  },
  {
    dayNumber: 9,
    time: '22:30',
    type: 'event',
    title: 'Paseo nocturno / hotel',
    description: 'Paseo final por Dotonbori y Namba antes de volver al hotel.',
    ...BLANK,
    destLat: 34.6687,
    destLng: 135.5013,
  },

  // Día 10
  {
    dayNumber: 10,
    time: '06:30',
    type: 'aviso',
    title: 'Levantarse temprano para USJ',
    description:
      'La web oficial todavía no publica el horario de octubre de 2026 y advierte que puede cambiar. Objetivo: llegar 60-90 minutos antes de la apertura oficial.',
    ...BLANK,
  },
  {
    dayNumber: 10,
    time: '07:00',
    type: 'comida',
    title: 'Desayuno rápido',
    description: 'Desayuno ligero antes de salir hacia Universal City.',
    ...BLANK,
  },
  {
    dayNumber: 10,
    time: '07:15',
    type: 'transport',
    title: 'Osaka - Universal City',
    description: 'Salir entre 07:15 y 07:30 para llegar sobre las 08:00 y hacer cola de entrada (operador JR).',
    ...BLANK,
    durationMin: 45,
    origin: 'Osaka',
    destination: 'Universal City Station',
    originLat: 34.6937,
    originLng: 135.5023,
    destLat: 34.6654,
    destLng: 135.4323,
  },
  {
    dayNumber: 10,
    time: '08:00',
    type: 'aviso',
    title: 'Cola de entrada USJ',
    description: 'Estar en la cola entre 08:00 y 09:00 si finalmente abre a las 09:00.',
    ...BLANK,
  },
  {
    dayNumber: 10,
    time: '09:00',
    type: 'event',
    title: 'Universal Studios Japan',
    description:
      'Día exclusivo para USJ. Prioridades: Super Nintendo World, Mario Kart: Koopa\'s Challenge, Yoshi\'s Adventure, Donkey Kong Country, The Wizarding World of Harry Potter, Forbidden Journey, Flight of the Hippogriff, Hollywood Dream, The Flying Dinosaur, JAWS. Nota: valorar Express Pass por Super Nintendo World y comer fuera de horas normales, sobre 11:00-11:30 o 14:00-14:30.',
    ...BLANK,
    status: 'pendiente',
    destLat: 34.6657,
    destLng: 135.4323,
  },
  {
    dayNumber: 10,
    time: '21:00',
    type: 'transport',
    title: 'Regreso a Osaka',
    description: 'Regreso a Osaka al cierre del parque (operador JR).',
    ...BLANK,
    durationMin: 45,
    origin: 'Universal City Station',
    destination: 'Osaka',
    originLat: 34.6654,
    originLng: 135.4323,
    destLat: 34.6937,
    destLng: 135.5023,
  },

  // Día 11
  {
    dayNumber: 11,
    time: '08:30',
    type: 'comida',
    title: 'Kuromon Ichiba Market',
    description:
      'Ir pronto para desayuno + brunch. Recorrer y compartir pequeñas raciones: atún, sushi, vieiras, wagyu, tamagoyaki, fruta, dashi y unagi.',
    ...BLANK,
    destLat: 34.6656,
    destLng: 135.5063,
  },
  {
    dayNumber: 11,
    time: '11:00',
    type: 'place',
    title: 'Den Den Town',
    description: 'La versión de Osaka de Akihabara: retro gaming, manga, anime, electrónica, figuras, PC y segunda mano.',
    ...BLANK,
    destLat: 34.6626,
    destLng: 135.5061,
  },
  {
    dayNumber: 11,
    time: '12:30',
    type: 'comida',
    title: 'Shinsekai + kushikatsu',
    description: 'Barrio retro alrededor de Tsutenkaku. Comer kushikatsu, una de las especialidades de Osaka. Subir a Tsutenkaku es opcional.',
    ...BLANK,
    destLat: 34.6524,
    destLng: 135.5061,
  },
  {
    dayNumber: 11,
    time: '15:00',
    type: 'place',
    title: 'Shinsaibashi-suji',
    description: 'Metro hacia Shinsaibashi. Gran galería comercial cubierta para compras y paseo urbano.',
    ...BLANK,
    destLat: 34.673,
    destLng: 135.5013,
  },
  {
    dayNumber: 11,
    time: '16:30',
    type: 'place',
    title: 'Amerikamura',
    description: 'Zona alternativa con ropa, vintage, sneakers, música y cafés. Recorrido recomendado: Amerikamura, Shinsaibashi y Namba.',
    ...BLANK,
    destLat: 34.6721,
    destLng: 135.4986,
  },
  {
    dayNumber: 11,
    time: '19:00',
    type: 'nota',
    title: 'Decisión de la noche',
    description: 'Opción recomendada: Umeda para cerrar Osaka con vistas. Alternativa: repetir Namba/Dotonbori si os gustó muchísimo.',
    ...BLANK,
  },
  {
    dayNumber: 11,
    time: '19:30',
    type: 'event',
    title: 'Umeda Sky Building',
    description: 'Subir al Kuchu Teien Observatory al anochecer. Muy buena forma de cerrar Osaka.',
    ...BLANK,
    destLat: 34.7053,
    destLng: 135.49,
  },
  {
    dayNumber: 11,
    time: '21:00',
    type: 'comida',
    title: 'Cena cerca de Osaka Station',
    description: 'Cena por Umeda u Osaka Station después del observatorio.',
    ...BLANK,
    destLat: 34.7024,
    destLng: 135.4959,
  },

  // Día 12
  {
    dayNumber: 12,
    time: '08:00',
    type: 'comida',
    title: 'Desayuno en Nagoya',
    description: 'Probar algo típico desde primera hora: ogura toast, café estilo kissaten, tamago o miso katsu si queréis algo más contundente.',
    ...BLANK,
    destLat: 35.1706,
    destLng: 136.8816,
  },
  {
    dayNumber: 12,
    time: '09:00',
    type: 'place',
    title: 'Nagoya Castle + Hommaru Palace',
    description:
      'Empezar aquí porque el castillo abre a las 09:00. Hommaru Palace merece mucho la pena por sus interiores reconstruidos. El recinto cierra a las 16:30 y la última entrada es a las 16:00.',
    ...BLANK,
    destLat: 35.1855,
    destLng: 136.8998,
  },
  {
    dayNumber: 12,
    time: '11:30',
    type: 'transport',
    title: 'Traslado a Osu',
    description: 'Metro hacia Osu Kannon.',
    ...BLANK,
    durationMin: 30,
    destination: 'Osu',
    destLat: 35.161,
    destLng: 136.9006,
  },
  {
    dayNumber: 12,
    time: '12:00',
    type: 'place',
    title: 'Osu Kannon + Osu Shopping Street',
    description:
      'Galerías comerciales cubiertas, tiendas retro, electrónica, manga/anime, segunda mano, gachapon y pequeños restaurantes. Más interesante que pasar horas en centros comerciales modernos.',
    ...BLANK,
    destLat: 35.161,
    destLng: 136.9006,
  },
  {
    dayNumber: 12,
    time: '14:00',
    type: 'comida',
    title: 'Miso katsu',
    description: 'Buscar miso katsu, cerdo empanado con salsa de miso rojo típica de Aichi. Alternativas: tebasaki, kishimen, doteni.',
    ...BLANK,
    destLat: 35.1706,
    destLng: 136.8816,
  },
  {
    dayNumber: 12,
    time: '15:00',
    type: 'place',
    title: 'Atsuta Jingu',
    description: 'Uno de los santuarios sintoístas más importantes de Japón. Da un contraste muy bueno respecto a la parte urbana de Nagoya.',
    ...BLANK,
    destLat: 35.1279,
    destLng: 136.9082,
  },
  {
    dayNumber: 12,
    time: '16:00',
    type: 'transport',
    title: 'Regreso hacia Sakae',
    description: 'Traslado desde Atsuta Jingu hacia Sakae para terminar el día por la zona moderna.',
    ...BLANK,
    durationMin: 60,
    origin: 'Atsuta Jingu',
    destination: 'Sakae',
    originLat: 35.1279,
    originLng: 136.9082,
    destLat: 35.1706,
    destLng: 136.9082,
  },
  {
    dayNumber: 12,
    time: '17:00',
    type: 'event',
    title: 'Oasis 21 + Mirai Tower',
    description: 'Zona moderna de Nagoya para esperar a que empiece a oscurecer. Oasis 21 tiene la estructura elevada de cristal Spaceship-Aqua.',
    ...BLANK,
    destLat: 35.1706,
    destLng: 136.9082,
  },
  {
    dayNumber: 12,
    time: '18:30',
    type: 'place',
    title: 'Sakae',
    description: 'Paseo por Hisaya-odori, Sakae, tiendas, arcades y Don Quijote si apetece.',
    ...BLANK,
    destLat: 35.1706,
    destLng: 136.9082,
  },
  {
    dayNumber: 12,
    time: '20:00',
    type: 'comida',
    title: 'Hitsumabushi',
    description:
      'Cena principal de Nagoya: unagi a la parrilla sobre arroz que se come en varias fases. Alternativa si no apetece anguila: tebasaki, cerveza e izakaya.',
    ...BLANK,
    destLat: 35.1706,
    destLng: 136.8816,
  },
  {
    dayNumber: 12,
    time: '21:30',
    type: 'nota',
    title: 'Volver al hotel',
    description: 'Dormir relativamente pronto porque el día siguiente conviene empezar temprano.',
    ...BLANK,
  },

  // Día 13
  {
    dayNumber: 13,
    time: '06:30',
    type: 'aviso',
    title: 'Levantarse temprano para Nakasendō',
    description: 'Desayuno rápido y comprar agua, fruta, onigiri o snack. No hace falta cargar mucha comida.',
    ...BLANK,
  },
  {
    dayNumber: 13,
    time: '07:00',
    type: 'transport',
    title: 'Nagoya - Nakatsugawa',
    description:
      'Opción rápida: Limited Express Shinano (operador JR). Los horarios publicados sitúan el trayecto en unos 48-50 minutos.',
    ...BLANK,
    durationMin: 48,
    origin: 'Nagoya Station',
    destination: 'Nakatsugawa',
    originLat: 35.1706,
    originLng: 136.8816,
    destLat: 35.4894,
    destLng: 137.5013,
  },
  {
    dayNumber: 13,
    time: '07:48',
    type: 'nota',
    title: 'Nakatsugawa',
    description: 'Minutos para baño, comprar bebida y localizar la parada del bus. La parada de Magome está delante de JR Nakatsugawa Station.',
    ...BLANK,
    destLat: 35.4894,
    destLng: 137.5013,
  },
  {
    dayNumber: 13,
    time: '09:10',
    type: 'transport',
    title: 'Bus Nakatsugawa - Magome',
    description:
      'El 09/10/2026 es viernes. No depender del servicio 08:15; con horario actual, el diario seguro sería 09:10 - 09:35. Revisar horarios de Kitaena antes del viaje.',
    ...BLANK,
    durationMin: 25,
    origin: 'Nakatsugawa Station',
    destination: 'Magome',
    originLat: 35.4894,
    originLng: 137.5013,
    destLat: 35.5236,
    destLng: 137.5661,
  },
  {
    dayNumber: 13,
    time: '09:35',
    type: 'place',
    title: 'Magome-juku',
    description: 'Dedicar 45-60 minutos antes de empezar la ruta: calle empedrada en pendiente, casas tradicionales, tiendas, cafés y vistas hacia el valle.',
    ...BLANK,
    destLat: 35.5236,
    destLng: 137.5661,
  },
  {
    dayNumber: 13,
    time: '10:30',
    type: 'event',
    title: 'Comienza la Nakasendō',
    description: 'Ruta Magome - Tsumago de unos 7,7 km. Dirección recomendada porque tras la subida inicial buena parte tiende a bajar hacia Tsumago.',
    ...BLANK,
    destLat: 35.5236,
    destLng: 137.5661,
  },
  {
    dayNumber: 13,
    time: '10:30',
    type: 'place',
    title: 'Magome - Magome Pass',
    description: 'Primera parte de la caminata: bosque y sendero tradicional. Probablemente la parte más exigente físicamente.',
    ...BLANK,
    destLat: 35.5236,
    destLng: 137.5661,
  },
  {
    dayNumber: 13,
    time: '11:15',
    type: 'place',
    title: 'Magome Pass - bosque',
    description: 'Bosque de cedros, caminos antiguos, pequeños pueblos, riachuelos y tramos de piedra originales.',
    ...BLANK,
  },
  {
    dayNumber: 13,
    time: '12:00',
    type: 'place',
    title: 'Otaki / Metaki waterfalls',
    description: 'Parada corta en las cascadas para descansar y comer algún snack.',
    ...BLANK,
    destLat: 35.5389,
    destLng: 137.5717,
  },
  {
    dayNumber: 13,
    time: '12:30',
    type: 'event',
    title: 'Camino hacia Tsumago',
    description: 'Uno de los tramos más bonitos de la caminata.',
    ...BLANK,
  },
  {
    dayNumber: 13,
    time: '13:30',
    type: 'place',
    title: 'Llegada a Tsumago-juku',
    description: 'Llegada sin prisa a una de las antiguas ciudades postales mejor conservadas.',
    ...BLANK,
    destLat: 35.5589,
    destLng: 137.5786,
  },
  {
    dayNumber: 13,
    time: '14:00',
    type: 'comida',
    title: 'Comida en Tsumago',
    description: 'Comer y recorrer el pueblo. Probar: soba, gohei mochi, oyaki y dulces de castaña.',
    ...BLANK,
    destLat: 35.5589,
    destLng: 137.5786,
  },
  {
    dayNumber: 13,
    time: '15:40',
    type: 'transport',
    title: 'Bus Tsumago - Nagiso',
    description: 'Objetivo: 15:40 - 15:48. Si queréis disfrutar más de Tsumago, alternativa 16:10 - 16:18.',
    ...BLANK,
    durationMin: 8,
    origin: 'Tsumago',
    destination: 'Nagiso',
    originLat: 35.5589,
    originLng: 137.5786,
    destLat: 35.5461,
    destLng: 137.5859,
  },
  {
    dayNumber: 13,
    time: '16:20',
    type: 'nota',
    title: 'Nagiso',
    description: 'Esperar tren. Si la conexión encaja bien, posiblemente no haga falta esperar mucho.',
    ...BLANK,
    destLat: 35.5461,
    destLng: 137.5859,
  },
  {
    dayNumber: 13,
    time: '17:00',
    type: 'transport',
    title: 'Nagiso - Nagoya',
    description: 'JR Chuo Line. Según combinación: Nagiso - Nakatsugawa - Nagoya o algún Limited Express que encaje.',
    ...BLANK,
    durationMin: 120,
    origin: 'Nagiso Station',
    destination: 'Nagoya',
    originLat: 35.5461,
    originLng: 137.5859,
    destLat: 35.1706,
    destLng: 136.8816,
  },
  {
    dayNumber: 13,
    time: '19:00',
    type: 'comida',
    title: 'Cena sencilla: tebasaki',
    description: 'Después de 8 km de senderismo, cena sencilla con tebasaki, las famosas alitas estilo Nagoya, cerveza y poco más.',
    ...BLANK,
    destLat: 35.1706,
    destLng: 136.8816,
  },

  // Día 14
  {
    dayNumber: 14,
    time: '06:30',
    type: 'aviso',
    title: 'Empezar Hakone temprano',
    description: 'Es sábado y Hakone puede llenarse bastante. Prioridad del día: Owakudani, Fuji, Lago Ashi, Hakone Shrine y onsen.',
    ...BLANK,
  },
  {
    dayNumber: 14,
    time: '07:00',
    type: 'transport',
    title: 'Salida hacia Hakone-Yumoto',
    description:
      'Salida temprana hacia Hakone-Yumoto (operadores JR / Odakyu Hakone), puerta de entrada para la ruta circular. Si la noche anterior seguís en Nagoya, conviene valorar avanzar hacia Odawara o Hakone para no empezar tarde. Nota: Hakone Freepass recomendado.',
    ...BLANK,
    durationMin: 90,
    destination: 'Hakone-Yumoto Station',
    destLat: 35.2323,
    destLng: 139.1069,
  },
  {
    dayNumber: 14,
    time: '08:30',
    type: 'nota',
    title: 'Hakone Freepass',
    description: 'El Hakone Freepass encaja muy bien para este día porque cubre trenes, buses, cable car, ropeway y el crucero turístico del Lago Ashi.',
    ...BLANK,
    destLat: 35.2323,
    destLng: 139.1069,
  },
  {
    dayNumber: 14,
    time: '08:30',
    type: 'transport',
    title: 'Hakone Tozan Railway',
    description: 'Hakone-Yumoto - Gora. Ferrocarril de montaña con curvas y cambios de sentido; ya forma parte de la experiencia.',
    ...BLANK,
    durationMin: 45,
    origin: 'Hakone-Yumoto',
    destination: 'Gora',
    originLat: 35.2323,
    originLng: 139.1069,
    destLat: 35.2452,
    destLng: 139.0563,
  },
  {
    dayNumber: 14,
    time: '09:15',
    type: 'transport',
    title: 'Hakone Tozan Cable Car',
    description: 'Gora - Sounzan. Subida corta antes de empezar la parte más espectacular del circuito.',
    ...BLANK,
    durationMin: 20,
    origin: 'Gora',
    destination: 'Sounzan',
    originLat: 35.2452,
    originLng: 139.0563,
    destLat: 35.2394,
    destLng: 139.0294,
  },
  {
    dayNumber: 14,
    time: '09:35',
    type: 'transport',
    title: 'Hakone Ropeway a Owakudani',
    description: 'Sounzan - Owakudani. Hacerlo lo antes posible para evitar gente y mejorar la probabilidad de ver el Monte Fuji por la mañana.',
    ...BLANK,
    durationMin: 25,
    origin: 'Sounzan',
    destination: 'Owakudani',
    originLat: 35.2394,
    originLng: 139.0294,
    destLat: 35.2436,
    destLng: 139.0192,
  },
  {
    dayNumber: 14,
    time: '10:00',
    type: 'place',
    title: 'Owakudani',
    description:
      'Zona volcánica activa con fumarolas, vapor, azufre, paisaje volcánico y vistas del Fuji si el cielo acompaña. Probar kuro-tamago, los huevos negros cocinados en aguas volcánicas.',
    ...BLANK,
    destLat: 35.2436,
    destLng: 139.0192,
  },
  {
    dayNumber: 14,
    time: '11:15',
    type: 'transport',
    title: 'Owakudani - Togendai',
    description: 'Segundo tramo del ropeway, especialmente bonito si está despejado: Lago Ashi, montañas y Monte Fuji.',
    ...BLANK,
    durationMin: 30,
    origin: 'Owakudani',
    destination: 'Togendai',
    originLat: 35.2436,
    originLng: 139.0192,
    destLat: 35.2131,
    destLng: 139.0128,
  },
  {
    dayNumber: 14,
    time: '12:00',
    type: 'transport',
    title: 'Crucero por Lago Ashi',
    description:
      'Togendai - Moto-Hakone en el barco turístico estilo pirata. Desde el lago se puede ver una de las imágenes clásicas de Hakone: Fuji, Lago Ashi y montañas.',
    ...BLANK,
    durationMin: 40,
    origin: 'Togendai',
    destination: 'Moto-Hakone',
    originLat: 35.2131,
    originLng: 139.0128,
    destLat: 35.2015,
    destLng: 139.0264,
  },
  {
    dayNumber: 14,
    time: '12:45',
    type: 'comida',
    title: 'Moto-Hakone + comida',
    description: 'Comida sin alargar demasiado: soba, tempura, pescado, curry japonés o donburi antes de visitar Hakone Shrine.',
    ...BLANK,
    destLat: 35.2015,
    destLng: 139.0264,
  },
  {
    dayNumber: 14,
    time: '14:00',
    type: 'place',
    title: 'Hakone Shrine + Heiwa no Torii',
    description:
      'Santuario entre cedros, escaleras y bajada al torii rojo dentro del Lago Ashi. Si la cola para la foto es enorme, no perder 40-60 minutos solo por la fotografía.',
    ...BLANK,
    destLat: 35.2013,
    destLng: 139.0261,
  },
  {
    dayNumber: 14,
    time: '15:00',
    type: 'event',
    title: 'Paseo Lago Ashi / antigua Tokaido',
    description:
      'Opción tranquila: caminar junto al lago. Opción histórica: hacer una pequeña sección de la antigua Tokaido para comparar con la Nakasendō del día anterior.',
    ...BLANK,
    destLat: 35.2015,
    destLng: 139.0264,
  },
  {
    dayNumber: 14,
    time: '16:00',
    type: 'transport',
    title: 'Regreso a Hakone-Yumoto',
    description:
      'Bus Moto-Hakone - Hakone-Yumoto. No dejar el regreso mucho más tarde porque dependéis de transporte local y el ropeway cierra relativamente pronto.',
    ...BLANK,
    durationMin: 60,
    origin: 'Moto-Hakone',
    destination: 'Hakone-Yumoto',
    originLat: 35.2015,
    originLng: 139.0264,
    destLat: 35.2323,
    destLng: 139.1069,
  },
  {
    dayNumber: 14,
    time: '17:00',
    type: 'event',
    title: 'Onsen en Hakone',
    description: 'Momento obligatorio después de la Nakasendō: onsen, idealmente en ryokan y mejor aún con rotenburo, baño exterior.',
    ...BLANK,
    destLat: 35.2323,
    destLng: 139.1069,
  },
  {
    dayNumber: 14,
    time: '19:00',
    type: 'comida',
    title: 'Cena en ryokan o Hakone-Yumoto',
    description: 'Si dormimos en ryokan, la elección clara sería cena kaiseki. Si no, restaurante o izakaya alrededor de Hakone-Yumoto.',
    ...BLANK,
    destLat: 35.2323,
    destLng: 139.1069,
  },

  // Día 15
  {
    dayNumber: 15,
    time: '10:00',
    type: 'transport',
    title: 'Hakone - Tokio',
    description:
      'Salida tranquila desde Hakone hacia Tokio (operadores Odakyu / JR). Ruta habitual: Hakone-Yumoto - Odawara - Tokyo, ajustando según la ubicación final del hotel.',
    ...BLANK,
    durationMin: 120,
    origin: 'Hakone-Yumoto Station',
    destination: 'Tokyo Station',
    originLat: 35.2323,
    originLng: 139.1069,
    destLat: 35.6812,
    destLng: 139.7671,
  },
  {
    dayNumber: 15,
    time: '12:00',
    type: 'nota',
    title: 'Hotel + dejar equipaje',
    description: 'Llegada al hotel de Tokio y dejar maletas. No hace falta esperar al check-in si permiten guardarlas.',
    ...BLANK,
    destLat: 35.6812,
    destLng: 139.7671,
  },
  {
    dayNumber: 15,
    time: '13:00',
    type: 'comida',
    title: 'Primera comida en Tokio',
    description: 'Buscar una comida sencilla: sushi, tempura, tendon o ramen, sin alargar demasiado el primer día.',
    ...BLANK,
    destLat: 35.6812,
    destLng: 139.7671,
  },
  {
    dayNumber: 15,
    time: '14:00',
    type: 'place',
    title: 'Asakusa: Kaminarimon, Nakamise-dori y Senso-ji',
    description: 'Buena introducción a Tokio: de la parte histórica a una megaciudad moderna en pocos minutos. Recorrer Kaminarimon, Nakamise-dori y Senso-ji.',
    ...BLANK,
    destLat: 35.7148,
    destLng: 139.7967,
  },
  {
    dayNumber: 15,
    time: '16:30',
    type: 'place',
    title: 'Sumida River',
    description: 'Paseo junto al río con vistas hacia Tokyo Skytree. No es imprescindible subir si luego haremos otros miradores.',
    ...BLANK,
    destLat: 35.7101,
    destLng: 139.8016,
  },
  {
    dayNumber: 15,
    time: '18:00',
    type: 'event',
    title: 'Akihabara',
    description:
      'Tarde-noche de electrónica, retro gaming, PC, anime, manga, arcades, gachapon y tiendas de segunda mano. Puntos: Yodobashi Akiba, Super Potato, Radio Kaikan, Bic Camera, Mandarake.',
    ...BLANK,
    destLat: 35.7022,
    destLng: 139.7745,
  },

  // Día 16
  {
    dayNumber: 16,
    time: '07:30',
    type: 'aviso',
    title: 'Sports Day en Tokio',
    description: 'El lunes 12 de octubre es festivo nacional. Habrá más movimiento en atracciones y transporte; por eso conviene centrar el día en barrios de Tokio.',
    ...BLANK,
  },
  {
    dayNumber: 16,
    time: '08:00',
    type: 'place',
    title: 'Meiji Jingu',
    description: 'Entrar temprano. Bosque enorme en pleno Tokio y contrapunto perfecto antes de Harajuku.',
    ...BLANK,
    destLat: 35.6764,
    destLng: 139.6993,
  },
  {
    dayNumber: 16,
    time: '09:30',
    type: 'place',
    title: 'Harajuku + Cat Street',
    description: 'Takeshita Street sin dedicar demasiado tiempo y después Cat Street hacia Omotesando.',
    ...BLANK,
    destLat: 35.6702,
    destLng: 139.7027,
  },
  {
    dayNumber: 16,
    time: '11:00',
    type: 'place',
    title: 'Omotesando',
    description: 'Arquitectura, tiendas y cafés. Se puede llegar andando desde Harajuku.',
    ...BLANK,
    destLat: 35.6654,
    destLng: 139.7124,
  },
  {
    dayNumber: 16,
    time: '12:30',
    type: 'comida',
    title: 'Gyukatsu o tonkatsu',
    description: 'Comida por Harajuku, Omotesando o Shibuya. Prioridad: gyukatsu; alternativa: tonkatsu.',
    ...BLANK,
    destLat: 35.6595,
    destLng: 139.7005,
  },
  {
    dayNumber: 16,
    time: '14:00',
    type: 'event',
    title: 'Shibuya',
    description: 'Cruce de Shibuya, Hachiko, Nintendo Tokyo, Pokémon Center, Capcom Store, Jump Shop y Center-gai.',
    ...BLANK,
    destLat: 35.6595,
    destLng: 139.7005,
  },
  {
    dayNumber: 16,
    time: '17:30',
    type: 'event',
    title: 'Shibuya Sky',
    description: 'Reservar sobre 17:00-17:30 para ver día, puesta de sol y Tokio de noche. Es uno de los miradores de pago que sí priorizaría.',
    ...BLANK,
    status: 'pendiente',
    destLat: 35.659,
    destLng: 139.7016,
  },
  {
    dayNumber: 16,
    time: '18:45',
    type: 'transport',
    title: 'Shibuya - Shinjuku',
    description: 'Trayecto rápido en Yamanote (operador JR) para terminar la noche en Shinjuku.',
    ...BLANK,
    durationMin: 15,
    origin: 'Shibuya',
    destination: 'Shinjuku',
    originLat: 35.6595,
    originLng: 139.7005,
    destLat: 35.6896,
    destLng: 139.7006,
  },
  {
    dayNumber: 16,
    time: '19:00',
    type: 'event',
    title: 'Shinjuku nocturno',
    description: 'Omoide Yokocho para cena/yakitori, Kabukicho y Godzilla Road, paseo por Golden Gai y regreso al hotel.',
    ...BLANK,
    destLat: 35.6896,
    destLng: 139.7006,
  },

  // Día 17
  {
    dayNumber: 17,
    time: '07:30',
    type: 'transport',
    title: 'Tokio - Kamakura',
    description: 'JR Yokosuka Line desde Tokyo Station. Kamakura encaja como excursión porque está a unos 55 minutos.',
    ...BLANK,
    durationMin: 60,
    origin: 'Tokyo Station',
    destination: 'Kamakura',
    originLat: 35.6812,
    originLng: 139.7671,
    destLat: 35.326,
    destLng: 139.5563,
  },
  {
    dayNumber: 17,
    time: '08:30',
    type: 'place',
    title: 'Tsurugaoka Hachimangu',
    description: 'Uno de los principales santuarios de Kamakura para empezar la excursión.',
    ...BLANK,
    destLat: 35.326,
    destLng: 139.5563,
  },
  {
    dayNumber: 17,
    time: '09:30',
    type: 'place',
    title: 'Komachi-dori',
    description: 'Calle comercial tradicional para picar matcha, senbei, dango, croquetas o algún snack.',
    ...BLANK,
    destLat: 35.3223,
    destLng: 139.5519,
  },
  {
    dayNumber: 17,
    time: '10:30',
    type: 'transport',
    title: 'Enoden: Kamakura - Hase',
    description: 'El propio tren merece la pena y conecta muy bien con el Gran Buda y Hasedera.',
    ...BLANK,
    durationMin: 30,
    origin: 'Kamakura',
    destination: 'Hase',
    originLat: 35.326,
    originLng: 139.5563,
    destLat: 35.3167,
    destLng: 139.5359,
  },
  {
    dayNumber: 17,
    time: '11:00',
    type: 'place',
    title: 'Gran Buda de Kamakura',
    description: 'Kotoku-in. Buda de bronce del siglo XIII y uno de los iconos de Kamakura.',
    ...BLANK,
    destLat: 35.3167,
    destLng: 139.5359,
  },
  {
    dayNumber: 17,
    time: '12:00',
    type: 'place',
    title: 'Hasedera',
    description: 'Templo muy cercano al Gran Buda, con jardines y vistas hacia el mar.',
    ...BLANK,
    destLat: 35.3138,
    destLng: 139.5342,
  },
  {
    dayNumber: 17,
    time: '13:00',
    type: 'comida',
    title: 'Comida de pescado',
    description: 'Kamakura y Shonan tienen buen producto marino. Buscar pescado, donburi o algo sencillo antes de ir a Enoshima.',
    ...BLANK,
    destLat: 35.3167,
    destLng: 139.5359,
  },
  {
    dayNumber: 17,
    time: '14:00',
    type: 'transport',
    title: 'Enoden hacia Enoshima',
    description: 'Traslado hacia la parte costera de la excursión.',
    ...BLANK,
    durationMin: 30,
    origin: 'Hase',
    destination: 'Enoshima',
    originLat: 35.3167,
    originLng: 139.5359,
    destLat: 35.2989,
    destLng: 139.4803,
  },
  {
    dayNumber: 17,
    time: '14:30',
    type: 'event',
    title: 'Enoshima',
    description:
      'Recorrer: Enoshima Benzaiten Nakamise, Enoshima Shrine, Samuel Cocking Garden, Sea Candle, costa y cuevas si el horario lo permite.',
    ...BLANK,
    destLat: 35.2989,
    destLng: 139.4803,
  },
  {
    dayNumber: 17,
    time: '17:30',
    type: 'place',
    title: 'Puesta de sol en Enoshima',
    description: 'Intentar estar en la zona alta de Enoshima. Con buena visibilidad también se puede ver el Fuji.',
    ...BLANK,
    destLat: 35.2989,
    destLng: 139.4803,
  },
  {
    dayNumber: 17,
    time: '18:30',
    type: 'transport',
    title: 'Regreso a Tokio',
    description: 'Regreso y cena cerca del hotel (operadores Enoden / JR). No meter nada más este día.',
    ...BLANK,
    durationMin: 90,
    origin: 'Enoshima',
    destination: 'Tokyo Station',
    originLat: 35.2989,
    originLng: 139.4803,
    destLat: 35.6812,
    destLng: 139.7671,
  },

  // Día 18
  {
    dayNumber: 18,
    time: '08:00',
    type: 'event',
    title: 'Tokyo DisneySea',
    description:
      '1-Day Passport para Tokyo DisneySea. Salir del hotel sobre las 07:00 y estar allí sobre las 08:00. Prioridades: Fantasy Springs, Journey to the Center of the Earth, Soaring, Raging Spirits, 20,000 Leagues Under the Sea. Cierres previstos: Tower of Terror, Indiana Jones Adventure, Mermaid Lagoon Theater. Ubicación: Tokyo DisneySea, Urayasu, Chiba, Japón.',
    status: 'programado',
    cost: 21800,
    currency: 'JPY',
    durationMin: null,
    origin: null,
    destination: null,
    originLat: null,
    originLng: null,
    destLat: 35.6267,
    destLng: 139.8853,
  },
  {
    dayNumber: 18,
    time: '20:00',
    type: 'event',
    title: 'Show nocturno / cierre de DisneySea',
    description: 'Quedarse hasta el final, entre 20:00 y 21:00, y volver después al hotel. Nada más planificado ese día.',
    ...BLANK,
    destLat: 35.6267,
    destLng: 139.8853,
  },

  // Día 19
  {
    dayNumber: 19,
    time: '07:30',
    type: 'comida',
    title: 'Tsukiji Outer Market',
    description: 'Ir temprano para desayunar/comer picando: sushi, sashimi, tamagoyaki, wagyu, vieiras o uni. Mejor no ir solo a restaurantes virales.',
    ...BLANK,
    destLat: 35.6654,
    destLng: 139.7707,
  },
  {
    dayNumber: 19,
    time: '09:30',
    type: 'place',
    title: 'Ginza',
    description: 'Paseo a pie desde Tsukiji. Arquitectura, Uniqlo Ginza, Itoya y Ginza Six.',
    ...BLANK,
    destLat: 35.6717,
    destLng: 139.765,
  },
  {
    dayNumber: 19,
    time: '11:30',
    type: 'place',
    title: 'Tokyo Station + Marunouchi',
    description: 'Paseo por Marunouchi y Tokyo Character Street para compras antes de comer algo ligero.',
    ...BLANK,
    destLat: 35.6812,
    destLng: 139.7671,
  },
  {
    dayNumber: 19,
    time: '13:00',
    type: 'comida',
    title: 'Comida ligera',
    description: 'Comida ligera para llegar bien a teamLab Borderless.',
    ...BLANK,
    destLat: 35.6812,
    destLng: 139.7671,
  },
  {
    dayNumber: 19,
    time: '14:30',
    type: 'event',
    title: 'teamLab Borderless',
    description: 'Azabudai Hills. Museo digital sin recorrido fijo, con obras conectadas entre salas. Conviene reservar entrada sobre 14:30-15:00 y dejar 2-2,5 horas.',
    ...BLANK,
    status: 'pendiente',
    destLat: 35.6605,
    destLng: 139.7423,
  },
  {
    dayNumber: 19,
    time: '17:00',
    type: 'place',
    title: 'Azabudai Hills',
    description: 'Paseo por Azabudai Hills después de teamLab.',
    ...BLANK,
    destLat: 35.6605,
    destLng: 139.7423,
  },
  {
    dayNumber: 19,
    time: '18:00',
    type: 'place',
    title: 'Tokyo Tower',
    description: 'Está cerca de Azabudai. No hace falta subir; la vista desde abajo al anochecer ya merece la pena.',
    ...BLANK,
    destLat: 35.6586,
    destLng: 139.7454,
  },
  {
    dayNumber: 19,
    time: '19:00',
    type: 'comida',
    title: 'Última cena en Roppongi',
    description: 'Última cena importante en Japón: yakiniku o sushi omakase, según presupuesto. Último paseo opcional hacia Shibuya o Shinjuku si queda energía.',
    ...BLANK,
    destLat: 35.6627,
    destLng: 139.7314,
  },

  // Día 20
  {
    dayNumber: 20,
    time: '08:30',
    type: 'event',
    title: 'Últimas compras',
    description: 'Elegir según dónde esté el hotel: Tokyo Station, Shibuya o Shinjuku. No cruzar Tokio innecesariamente y no planificar nada importante después de las 11:00.',
    ...BLANK,
    destLat: 35.6812,
    destLng: 139.7671,
  },
  {
    dayNumber: 20,
    time: '10:30',
    type: 'nota',
    title: 'Recoger maletas',
    description: 'Volver al hotel sobre las 10:30-11:00 para recoger maletas y salir hacia Narita con margen.',
    ...BLANK,
  },
  {
    dayNumber: 20,
    time: '13:00',
    type: 'aviso',
    title: 'Llegar a Narita',
    description: 'Hora límite recomendada: 13:00-13:15 en el Aeropuerto Internacional de Narita para el vuelo de las 16:20.',
    ...BLANK,
    destLat: 35.7719,
    destLng: 140.3929,
  },
  {
    dayNumber: 20,
    time: '16:20',
    type: 'transport',
    title: 'Tokio - Barcelona',
    description:
      'Vuelo de vuelta con escala nocturna en Hong Kong (Cathay Pacific CX549 / CX321). El coste ya está registrado en el vuelo de ida (importe único de ida/vuelta).',
    ...BLANK,
    durationMin: 1395,
    origin: 'NRT Aeropuerto Internacional de Narita',
    destination: 'Barcelona',
    originLat: 35.7719,
    originLng: 140.3929,
    destLat: 41.2971,
    destLng: 2.0785,
    viaLabel: 'Escala en Hong Kong',
    viaLat: 22.308,
    viaLng: 113.9185,
  },
];

export type AccommodationSeed = {
  name: string;
  checkIn: string;
  checkOut: string;
  nights: number | null;
  cost: number | null;
  currency: 'EUR' | 'JPY' | null;
  status: 'programado' | 'confirmado' | 'pendiente';
  address: string | null;
  lat: number | null;
  lng: number | null;
  notes: string | null;
};

export const accommodationSeeds: AccommodationSeed[] = [
  {
    name: 'Hotel Torifito Hakata Gion',
    checkIn: '2026-09-28',
    checkOut: '2026-09-30',
    nights: 2,
    cost: 163.0,
    currency: 'EUR',
    status: 'programado',
    address: 'Hakata-ku Reisenmachi 8-24, Fukuoka, Japón',
    lat: 33.5926,
    lng: 130.4159,
    notes: null,
  },
  {
    name: 'Yufuin Onsen Toshoan',
    checkIn: '2026-09-30',
    checkOut: '2026-10-01',
    nights: 1,
    cost: 303.0,
    currency: 'EUR',
    status: 'programado',
    address: 'Yufuincho Kawaminami 1044-1, Yufu, Oita, Japón',
    lat: 33.2645,
    lng: 131.3626,
    notes: 'Ryokan onsen.',
  },
  {
    name: 'Hotel Arthur KITAHAMA BASE',
    checkIn: '2026-10-01',
    checkOut: '2026-10-02',
    nights: 1,
    cost: null,
    currency: null,
    status: 'confirmado',
    address: 'Kitahama 1-2-5, Beppu, Oita, Japón',
    lat: 33.2846,
    lng: 131.4914,
    notes: 'Habitación cama grande, 2 adultos.',
  },
  {
    name: 'Dormir en Matsuyama',
    checkIn: '2026-10-02',
    checkOut: '2026-10-03',
    nights: null,
    cost: null,
    currency: null,
    status: 'pendiente',
    address: null,
    lat: 33.8392,
    lng: 132.7657,
    notes: 'Alojamiento pendiente por definir.',
  },
  {
    name: 'Dormir en Takamatsu',
    checkIn: '2026-10-03',
    checkOut: '2026-10-04',
    nights: null,
    cost: null,
    currency: null,
    status: 'pendiente',
    address: null,
    lat: 34.3401,
    lng: 134.0466,
    notes: 'Alojamiento pendiente por definir.',
  },
  {
    name: 'Dormir en Kurashiki',
    checkIn: '2026-10-04',
    checkOut: '2026-10-05',
    nights: null,
    cost: null,
    currency: null,
    status: 'pendiente',
    address: null,
    lat: 34.5847,
    lng: 133.772,
    notes: 'Alojamiento pendiente por definir.',
  },
];

export const checklistSeeds: string[] = [
  'Confirmar alojamientos de Beppu, Matsuyama, Takamatsu y Kurashiki.',
  'Añadir/confirmar hoteles de Osaka, Nagoya, Hakone y Tokio, que no están detallados como reservas en el JSON.',
  'Comprar Universal Studios Japan y valorar Express Pass.',
  'Reservar Chichu Art Museum en Naoshima.',
  'Reservar Shibuya Sky (franja recomendada 17:00–17:30).',
  'Reservar teamLab Borderless (franja recomendada 14:30–15:00).',
  'Revisar horario definitivo del bus Nakatsugawa → Magome antes del 9 de octubre.',
  'Revisar horarios definitivos de USJ y cierres de atracciones para octubre de 2026.',
  'Valorar Hakone Freepass para el circuito del 10 de octubre.',
  'Completar límites de equipaje de Cathay Pacific si aún no están confirmados.',
];
